<!-- 本组件拥有单条入库明细的完整编辑区；它不选择物品、不提交整张入库单，也不管理路由。 -->
<template>
  <div class="inbound-line-editor">
    <section class="inbound-line-editor__operation-fields" :aria-label="$t('stockDraft.inboundParametersAria')">
      <label>
        <span>{{ $t('common.amount') }} *</span>
        <input
          v-model.number="line.quantity"
          :name="'quantity_' + line.lineId"
          :data-line-id="line.lineId"
          data-field="quantity"
          :class="{
            'inbound-control--error': validationAttempted && !validQuantity(line.quantity),
          }"
          :aria-invalid="validationAttempted && !validQuantity(line.quantity) ? true : undefined"
          :aria-describedby="
            validationAttempted && !validQuantity(line.quantity)
              ? `inbound-${line.lineId}-quantity-error`
              : undefined
          "
          type="number"
          min="0.01"
          step="0.01"
          inputmode="decimal"
          :aria-label="$t('stockDraft.inboundQuantityAria', { name: line.item.name })"
          autofocus
        />
        <span
          v-if="validationAttempted && !validQuantity(line.quantity)"
          :id="`inbound-${line.lineId}-quantity-error`"
          class="visually-hidden"
          role="alert"
          >{{ $t('stockDraft.inboundQuantityPositive') }}</span
        >
      </label>
      <label>
        <span>{{ $t('stockDraft.unitPrice') }} *</span>
        <input
          v-model.number="line.unitPrice"
          :name="'unit_price_' + line.lineId"
          :data-line-id="line.lineId"
          data-field="unitPrice"
          :class="{
            'inbound-control--error': validationAttempted && !validUnitPrice(line.unitPrice),
          }"
          :aria-invalid="validationAttempted && !validUnitPrice(line.unitPrice) ? true : undefined"
          :aria-describedby="
            validationAttempted && !validUnitPrice(line.unitPrice)
              ? `inbound-${line.lineId}-unit-price-error`
              : undefined
          "
          type="number"
          min="0"
          step="0.01"
          inputmode="decimal"
          :aria-label="$t('stockDraft.inboundUnitPriceAria', { name: line.item.name })"
        />
        <span
          v-if="validationAttempted && !validUnitPrice(line.unitPrice)"
          :id="`inbound-${line.lineId}-unit-price-error`"
          class="visually-hidden"
          role="alert"
          >{{ $t('stockDraft.inboundUnitPriceNonNegative') }}</span
        >
      </label>
      <label>
        <span>{{ $t('stockDraft.inboundLocationField') }} *</span>
        <SelectControl
          v-model="line.locationId"
          :name="'location_' + line.lineId"
          :data-line-id="line.lineId"
          data-field="locationId"
          :aria-invalid="validationAttempted && line.locationId === null ? true : undefined"
          :aria-label="$t('stockDraft.inboundLocationAria', { name: line.item.name })"
          compact
        >
          <option :value="null">{{ $t('stockDraft.pleaseSelect') }}</option>
          <optgroup v-for="group in locationGroups" :key="group.name" :label="group.name">
            <option v-for="location in group.locations" :key="location.id" :value="location.id">
              {{ location.name }}
            </option>
          </optgroup>
        </SelectControl>
      </label>
    </section>

    <div class="inbound-line-editor__base-fields">
      <label>
        <span>{{ $t('stockDraft.batchNoField') }}</span>
        <input
          v-model="line.batchNo"
          :name="'batch_no_' + line.lineId"
          type="text"
          maxlength="128"
          :placeholder="$t('stockDraft.batchNoAutoGenerated')"
        />
      </label>
      <label>
        <span>{{ $t('stockDraft.expiryField') }}</span>
        <input v-model="line.expiresAt" :name="'expires_at_' + line.lineId" type="date" />
      </label>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, watch } from "vue";
import { useI18n } from "vue-i18n";
import type { LocationResponse } from "../../api/locations";
import {
  validQuantity,
  validUnitPrice,
  type InboundDraftLine,
} from "../../pages/inbound-draft/model";
import SelectControl from "../forms/SelectControl.vue";
import { notice } from "../../notices/notice";

const { t } = useI18n();

const props = defineProps<{
  line: InboundDraftLine;
  locations: LocationResponse[];
  locationError: string;
  validationAttempted: boolean;
}>();

const emit = defineEmits<{
  "retry-locations": [];
}>();

watch(
  () => props.locationError,
  (error) => {
    if (error)
      notice.error(t("stockDraft.loadLocationsFailed"), {
        detail: error,
        onClick: () => emit("retry-locations"),
      });
  },
);

const locationGroups = computed(() => {
  const groups = new Map<string, LocationResponse[]>();
  for (const location of props.locations) {
    const list = groups.get(location.group_name) ?? [];
    list.push(location);
    groups.set(location.group_name, list);
  }
  return Array.from(groups, ([name, locations]) => ({ name, locations }));
});
</script>
