<!-- 本组件只读呈现入库审批明细和增加库存后果；它不修改单据或执行审批。 -->
<template>
  <section class="approval-detail-lines">
    <h3>
      {{ $t('approvals.inboundItemsLabel') }} <span>{{ $t('approvals.lineCount', { n: order.items.length }) }}</span>
    </h3>
    <article v-for="item in order.items" :key="item.id">
      <header>
        <AuthenticatedImage
          :file-id="item.item_image_file_id"
          :alt="$t('approvals.itemMainImage', { name: item.item_name })"
          :size="52"
          previewable
        />
        <div>
          <strong>{{ item.item_name }}</strong
          ><small>{{ item.item_sku }} · {{ item.item_unit }} · {{ $t('approvals.itemRef', { n: item.item_id }) }}</small>
        </div>
        <b>¥{{ money(item.quantity * item.unit_price) }}</b>
      </header>
      <dl>
        <div>
          <dt>{{ $t('common.amount') }}</dt>
          <dd>{{ item.quantity }} {{ item.item_unit }}</dd>
        </div>
        <div>
          <dt>{{ $t('approvals.unitPrice') }}</dt>
          <dd>¥{{ money(item.unit_price) }}</dd>
        </div>
        <div>
          <dt>{{ $t('approvals.targetLocation') }}</dt>
          <dd>{{ item.location_name }}</dd>
        </div>
        <div>
          <dt>{{ $t('approvals.batch') }}</dt>
          <dd>{{ item.batch_no || $t('approvals.autoGenerated') }}</dd>
        </div>
        <div>
          <dt>{{ $t('approvals.expiry') }}</dt>
          <dd>{{ item.expires_at || $t('approvals.notSet') }}</dd>
        </div>
      </dl>
    </article>
  </section>
</template>
<script setup lang="ts">
import type { InboundOrderResponse } from "../../api/inboundOrders";
import AuthenticatedImage from "../attributes/AuthenticatedImage.vue";
defineProps<{ order: InboundOrderResponse }>();
function money(value: number): string {
  return new Intl.NumberFormat("zh-CN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
}
</script>
